-- INSERT DATA INTO DIVISION TABLE
INSERT INTO DIVISION (NAME, ACTIVE, CREATED_AT, UPDATED_AT) VALUES
    ('Dhaka', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rajshahi', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- INSERT DATA INTO DISTRICT TABLE
INSERT INTO DISTRICT (NAME, ACTIVE, DIVISION_ID, CREATED_AT, UPDATED_AT) VALUES
    ('Dhaka', TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Gazipur', TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rajshahi', TRUE, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Chapainawabganj',  TRUE, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- INSERT DATA INTO UPAZILA TABLE
INSERT INTO UPAZILA (NAME, ACTIVE, DISTRICT_ID, CREATED_AT, UPDATED_AT) VALUES
    -- UPAZILA UNDER DHAKA
    ('Tangail Sadar',  TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sakhipur',  TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Basail',  TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- UPAZILA UNDER CHAPAINAWABGANJ
    ('Bholahat',  TRUE, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Gomastapur',  TRUE, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Nachole',  TRUE, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Chapainawabganj Sadar',  TRUE, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shibganj', TRUE, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- INSERT DATA INTO SUBJECT TABLE
INSERT INTO SUBJECT (SUBJECT_NAME, CREATED_AT, UPDATED_AT) VALUES
    ('Bangla',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('General Math',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Higher Math',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ICT',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Social Science',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('General Science', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--- INSERT DATA INTO RATING TABEL
-- INSERT INTO CONTENT_RATING (STAR, RATING_TYPE) VALUES
--     ('*', 'BRONZE'),
--     ('**', 'SILVER'),
--     ('***', 'GOLD'),
--     ('****', 'PLATINUM'),
--     ('*****', 'DIAMOND');
